### ISSUE TITLE
Organize tables and indexes under "database" section

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#119]
Per discussion on 4/6.

**Comment by User0847** [comment]
To me the term "database" implies a separate system (a DBMS), rather than a data structure, which is a more accurate description of the items found under "records". If "records" is inadequate, how about "structures", "sets", "frames" or "arrays"?  (I like "structures" best, since it also covers linked lists and other forms that records can be used to create, but it may be a bit abstract, or too long as a header.)

**Comment by brian-swan** [comment]
"Database" was arrived at because tables and indexes mimic databases in many ways (structured rows of data that are persisted between script executions). Tables and indexes provide a vehicle for introducing concepts associated with databases.
