### ISSUE TITLE
Preserve user-added art and strings in tutorials

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#15]
There needs to be a way to create a tutorial that allows a user to add art and/or strings and preserve those throughout the tutorial. Currently, user-added images/strings can "revert" to the art/strings used when the tutorial was created (author-added art). This tutorial provides an example: http://tdev.ly/yzwiwwbf. Look at #2-5 main() in the tutorial. Because of the way I'm using {stauto}, user images and strings aren't preserved throughout the tutorial (the images I used when creating the tutorial are used instead).

**Comment by mmoskal** [comment]
The {stauto} should now preserve custom strings and art. The way it works is by mapping source strings and art names to the ones user entered. This means that you'll most likely want to use different strings in every place, because otherwise all the same strings in the template will be replaced with the same (last) customized string.

Other than that, it should work.

**Comment by brian-swan** [comment]
I think that maybe I don't understand how this works. In this tutorial, http://tdev.ly/ysova, I'm still seeing that user-added art changes part way through the tutorial (I'm on /app/latest). Am I doing something wrong?

**Comment by mmoskal** [comment]
It works for me, on my local build.

Are you running 80141?

We'll be uploading the changelog of builds together with them, so you can verify that you're running the right version.

**Comment by brian-swan** [comment]
I wasn't on 80141...am now and it works perfectly! Thanks!
