### ISSUE TITLE
Tutorial: Need to keep "Let's do it" button visible at all times

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#230]
New coders, and coders new to the TouchDevelop environment have a difficult time with tutorials if the "let's do it" button that takes them to the next tutorial step isn't always visible on-screen.  

This bug is a request to update the tutorial text boxes that appear between each tutorial step to:
1.  Always keep the "let's do it" button visible so that the new coder won't get lost.
2.  Rescale the font size to keep as much visible as possible in a single screen. OR
3.  Make the scroll bar, or some indicator that there's more text read, very visible - like adding a down arrow or downwards triangle that uses the same yellow highlight flash as other UI pieces that require the coder's attention.

**Comment by pelikhan** [comment]
If there is a lot of text, it also means that learners might just not read it. In fact, if they were reading the text they would automatically scroll the button within the view.

Sent from Outlook<http://taps.io/outlookmobile>




On Tue, Jun 23, 2015 at 10:07 AM -0700, "millerv" <notifications@github.com<mailto:notifications@github.com>> wrote:


New coders, and coders new to the TouchDevelop environment have a difficult time with tutorials if the "let's do it" button that takes them to the next tutorial step isn't always visible on-screen.

This bug is a request to update the tutorial text boxes that appear between each tutorial step to:
1. Always keep the "let's do it" button visible so that the new coder won't get lost.
2. Rescale the font size to keep as much visible as possible in a single screen. OR
3. Make the scroll bar, or some indicator that there's more text read, very visible - like adding a down arrow or downwards triangle that uses the same yellow highlight flash as other UI pieces that require the coder's attention.

-

**Comment by millerv** [comment]
So the situation that we're running into is even with succinct text written in the boxes without a scroll bar, localization into other languages will result in longer text than the original English text.

Also, from discussions with Brian Swan about this very same situation, there are known problems with usability when the "Let's do it" button is too low - students and young coders don't see the subtle scroll bar and lose their way since the button isn't visible enough.
