### ISSUE TITLE
Tutorials: Splash text function can lockup/crash tutorial if optional seconds used, custom text stomped over by "Get Ready!"

### ISSUE THREAD

**Issue by millerv** [Microsoft/TouchDevelop#234]
The tutorial in question that I've been working on is a hidden publish:  http://tdev.ly/kiduewcj

Steps to reproduce:
1. Go to the link: http://tdev.ly/kiduewcj
2. Go into the tutorial script itself and add a time - like 3 seconds to the splash text function towards the end of the script.
3. Otherwise, just leave the time off and add custom text instead of "Get Ready!"
4. Follow the tutorial steps and attempt to complete the tutorial's later splash text step.

Result: 
The tutorial displays purple warning messages and distorted color text boxes (in Beginner mode) where the learner tries to add the time.  If they don't try adding a time duration to show the text, the tutorial won't let them enter any custom text - it auto-fills with "Get Ready!"

Expected:
The splash text optional duration in seconds needs to allow the learner to enter a time without issue during the tutorial step, and if there's custom text from the tutorial writer, the learner needs a chance to change the "Get Ready!" text into what the tutorial writer intended.

Notes:
Here is a screenshot of the "Get Ready" text sticking.
![td_tutorial_auto_getready_splash](https://cloud.githubusercontent.com/assets/2482509/8344837/5fd99f4e-1a9b-11e5-9dfa-ebaedb9570b7.PNG)

**Comment by pelikhan** [comment]
Optional arguments are not yet supported in the tutorial engine.

Sent from Outlook<http://taps.io/outlookmobile>




On Wed, Jun 24, 2015 at 6:06 PM -0700, "millerv" <notifications@github.com<mailto:notifications@github.com>> wrote:


The tutorial in question that I've been working on is a hidden publish: http://tdev.ly/kiduewcj

Steps to reproduce:
1. Go to the link: http://tdev.ly/kiduewcj
2. Go into the tutorial script itself and add a time - like 3 seconds to the splash text function towards the end of the script.
3. Otherwise, just leave the time off and add custom text instead of "Get Ready!"
4. Follow the tutorial steps and attempt to complete the tutorial's later splash text step.

Result:
The tutorial displays purple warning messages and distorted color text boxes (in Beginner mode) where the learner tries to add the time. If they don't try adding a time duration to show the text, the tutorial won't let them enter any custom text - it auto-fills with "Get Ready!"

Expected:
The splash text optional duration in seconds needs to allow the learner to enter a time without issue during the tutorial step, and if there's custom text from the tutorial writer, the learner needs a chance to change the "Get Ready!" text into what the tutorial writer intended.

Notes:
Here is a screenshot of the "Get Ready" text sticking.
[td_tutorial_auto_getready_splash]<https://cloud.githubusercontent.com/assets/2482509/8344837/5fd99f4e-1a9b-11e5-9dfa-ebaedb9570b7.PNG>

-
