### ISSUE TITLE
Touchdevelop - Regarding conversion of Image-base64 string conversions.

### ISSUE THREAD

**Issue by tejasharne** [Microsoft/TouchDevelop#239]
I am getting an image (encoded in base64 string format) from a server. This base64-encoded string has to be converted back to image. I am doing in two steps:

1) Convert the base64 encoded string into a buffer - Using bits -> string to buffer(string,"base64") 
2) Write the buffer into a picture(of same dimensions) - Using Picture -> write buffer(buffer)  and then I'm displaying the picture.

The base64 string from the server (whole string):  "iVBORw0KGgoAAAANSUhEUgAAAJEAAAAeCAYAAAAsPvwuAAAAmUlEQVR42u3SQQoAIQgAwL7h/x+6sQsLHcqCPI7QITGNmvYsIiK+leX+/ZjPcifnsnvs5pzW3PaunLGrm/W6eZPqv3yjQQQRRBBBBBFEEEEEEUQQQQQRRBBBBBFEEEEEEUQQQQQRRBBBBBFEEEEEEUQQQQQRRBBBBBFEEEEEEUQQQQQRRBBBBBFEEEEEEUQQQQQRRBBBVIuoAwQlLkAhgPjNAAAAAElFTkSuQmCC"
The problem is: I am not getting the desired image when I display it on the wall. It just shows a very small image.

So I tried finding what string touchdevelop expected in  bits -> string to buffer(string,"base64") method. 
1) I obtained the original image from online convertor like - http://www.motobit.com/util/base64-decoder-encoder.asp supplying the same string as obtained from the server. This image was correct.
2) Then I did the reverse process of what I described above – Converting an image into base64 string. This, I did by using Picture to buffer(Picture) and then buffer to string(“base64“) and displayed the base64 string as generated by Touchdevelop for the same image.

The base64 string I got from TouchDevelop (just a small part of actual string - Actual string size-23,300 chars): 
“////////////////////////////////GRkZ/xkZGf////////////////8ZGRn/GRkZ////////////GRkZ/xkZGf8ZGRn/GRkZ//////8ZGRn/GRkZ/xkZGf8ZGRn//////xkZGf8ZGRn///////////8ZGRn/GRkZ/xkZGf8ZGRn//////xkZGf8ZGRn//////////////////////xkZGf8ZGRn//////xkZGf8ZGRn//////xkZGf8ZGRn/GRkZ/xkZGf///////////xkZGf8ZGRn//////xkZGf8ZGRn/GRkZ/xkZGf//////////////////////GRkZ/xkZGf//////GRkZ/xkZGf//////GRkZ/xkZGf8ZGRn/GRkZ////////////GRkZ/xkZGf8ZGRn/GRkZ//////8ZGRn/GRkZ/xkZGf8ZGRn//////////////////////xkZGf8ZGRn//////xkZGf8ZGRn//////xkZGf8ZGRn///////////8ZGRn/GRkZ//////8ZGRn/GRkZ//////////////////////8ZGRn/GRkZ/xkZGf8ZGRn//////xkZGf8ZGRn//////xkZGf8ZGRn/GRkZ/xkZGf///////////xkZGf8ZGRn/////////////////GRkZ/xkZGf///////////xkZGf8ZGRn/GRkZ/xkZGf//////GRkZ/xkZGf8ZGRn/GRkZ//////8ZGRn/GRkZ/////////////////////////////////////////////////xkZGf8ZGRn/////////////////GRkZ/xkZGf///////////xkZGf8ZGRn/GRkZ/xkZGf//////GRkZ/xkZGf8ZGRn/GRkZ//////8ZGRn/GRkZ////////////GRkZ/xkZGf8ZGRn/GRkZ……”

As you might have noticed, the base64 string from the server and the base64 string what touchdevelop expects to show the correct image, have a huge difference. And this is resulting into displaying of an incorrect image. I am stuck in this problem for a few days. Is there a bug or something?

**Comment by pelikhan** [comment]
You could simply create a data uri, append the base64 data and do web->picture on it.

Sent from Outlook<http://taps.io/outlookmobile>




On Tue, Jul 7, 2015 at 11:43 PM -0700, "tejasharne" <notifications@github.com<mailto:notifications@github.com>> wrote:


I am getting an image (encoded in base64 string format) from a server. This base64-encoded string has to be converted back to image. I am doing in two steps:

1) Convert the base64 encoded string into a buffer - Using bits -> string to buffer(string,"base64")
2) Write the buffer into a picture(of same dimensions) - Using Picture -> write buffer(buffer) and then I'm displaying the picture.

The base64 string from the server (whole string): "iVBORw0KGgoAAAANSUhEUgAAAJEAAAAeCAYAAAAsPvwuAAAAmUlEQVR42u3SQQoAIQgAwL7h/x+6sQsLHcqCPI7QITGNmvYsIiK+leX+/ZjPcifnsnvs5pzW3PaunLGrm/W6eZPqv3yjQQQRRBBBBBFEEEEEEUQQQQQRRBBBBBFEEEEEEUQQQQQRRBBBBBFEEEEEEUQQQQQRRBBBBBFEEEEEEUQQQQQRRBBBBBFEEEEEEUQQQQQRRBBBVIuoAwQlLkAhgPjNAAAAAElFTkSuQmCC"
The problem is: I am not getting the desired image when I display it on the wall. It just shows a very small image.

So I tried finding what string touchdevelop expected in bits -> string to buffer(string,"base64") method.
1) I obtained the original image from online convertor like - http://www.motobit.com/util/base64-decoder-encoder.asp supplying the same string as obtained from the server. This image was correct.
2) Then I did the reverse process of what I described above - Converting an image into base64 string. This, I did by using Picture to buffer(Picture) and then bits -> buffer to string("base64") and displayed the base64 string as generated by Touchdevelop for the same image.

The base64 string I got from TouchDevelop (just a small part of actual string - Actual string size-23,300 chars):
"////////////////////////////////GRkZ/xkZGf////////////////8ZGRn/GRkZ////////////GRkZ/xkZGf8ZGRn/GRkZ//////8ZGRn/GRkZ/xkZGf8ZGRn//////xkZGf8ZGRn///////////8ZGRn/GRkZ/xkZGf8ZGRn//////xkZGf8ZGRn//////////////////////xkZGf8ZGRn//////xkZGf8ZGRn//////xkZGf8ZGRn/GRkZ/xkZGf///////////xkZGf8ZGRn//////xkZGf8ZGRn/GRkZ/xkZGf//////////////////////GRkZ/xkZGf//////GRkZ/xkZGf//////GRkZ/xkZGf8ZGRn/GRkZ////////////GRkZ/xkZGf8ZGRn/GRkZ//////8ZGRn/GRkZ/xkZGf8ZGRn//////////////////////xkZGf8ZGRn//////xkZGf8ZGRn//////xkZGf8ZGRn///////////8ZGRn/GRkZ//////8ZGRn/GRkZ//////////////////////8ZGRn/GRkZ/xkZGf8ZGRn//////xkZGf8ZGRn//////xkZGf8ZGRn/GRkZ/xkZGf///////////xkZGf8ZGRn/////////////////GRkZ/xkZGf///////////xkZGf8ZGRn/GRkZ/xkZGf//////GRkZ/xkZGf8ZGRn/GRkZ//////8ZGRn/GRkZ/////////////////////////////////////////////////xkZGf8ZGRn/////////////////GRkZ/xkZGf///////////xkZGf8ZGRn/GRkZ/xkZGf//////GRkZ/xkZGf8ZGRn/GRkZ//////8ZGRn/GRkZ////////////GRkZ/xkZGf8ZGRn/GRkZ......"

As you might have noticed, the base64 string from the server and the base64 string what touchdevelop expects to show the correct image, have a huge difference. And this is resulting into displaying of an incorrect image. I am stuck in this problem for a few days. Is there a bug or something?

-

**Comment by tejasharne** [comment]
Although I didn't really understand what I was doing wrong with buffers, but your way worked perfectly! Thanks a lot :) !

I just wanted to ask another question not related to this topic...

Why don't TouchDevelop support gif images?
I have a series of 24 png images which I wanted to show sequentially resulting into a small animation. I thought converting those pngs to a gif might be a solution but later ended up finding out that gifs are not supported by TouchDevelop. So I tried to figure out my way through sprite animation but I failed. Can you please suggest me what should I do for that sequential image animation?

**Comment by pelikhan** [comment]
You can use the Sprite Sheet support to create animation.

See board->create sprite sheet

We use the canvas to render the game board and it does not support animated gifs.

Sent from Outlook<http://taps.io/outlookmobile>




On Thu, Jul 9, 2015 at 12:41 AM -0700, "tejasharne" <notifications@github.com<mailto:notifications@github.com>> wrote:


Although I didn't really understand what I was doing wrong with buffers, but your way worked perfectly! Thanks a lot :) !

I just wanted to ask another question not related to this topic...

Why don't TouchDevelop support gif images?
I have a series of 24 png images which I wanted to show sequentially resulting into a small animation. I thought converting those pngs to a gif might be a solution but later ended up finding out that gifs are not supported by TouchDevelop. So I tried to figure out my way through sprite animation but I failed. Can you please suggest me what should I do for that sequential image animation?

-

**Comment by tejasharne** [comment]
Can I have animation on an atomic page with or without using sprites?

**Comment by pelikhan** [comment]
You might be able to load animated gifs from your own domains.

Sent from Outlook<http://taps.io/outlookmobile>




On Thu, Jul 9, 2015 at 5:54 AM -0700, "tejasharne" <notifications@github.com<mailto:notifications@github.com>> wrote:


Can I have animation on an atomic page with or without using sprites?

-

**Comment by tejasharne** [comment]
Thanks, I did the same as the way you suggested before, for base64 strings (using data uri of  the gif).
