### ISSUE TITLE
Cordova Should Target Windows 10

### ISSUE THREAD

**Issue by ianapps** [Microsoft/TouchDevelop#274]
With the imminent release of Windows Phone 10, Cordova Apps should target Windows 10 rather than 8.1 as they do at present.

**Comment by pelikhan** [comment]
What command line do you use for that? Do you have a PR?

**Comment by ianapps** [comment]
Hi Peli, can I hold on answering this.  The latest VS2015 updates seem to have incorporated most of the manual work that I had to do.  Only one change now seems necessary and that is to change the target to 10.0 in the config file: <preference name="windows-target-version" value="10.0" />

**Comment by ianapps** [comment]
Confirmed, the above is all that is required to build universal apps.

**Comment by pelikhan** [comment]
I can't see the above. Am I missing something?

**Comment by ianapps** [comment]
It's in the exported code, You may not have any control of it, it may be a Cordova thing. The only thing i have to do now to generate a Universal app (that passes store certification) is make some images as Win10 image sizes are different from Win8.1 and update the plugins because they point to the wrong repository when TD generates the code. Overall I am delighted with TD and the work you and your team are doing - it's come a long way in the last 2 or 3 years.

**Comment by pelikhan** [comment]
Could you dig which command line option they use?

Sent from Outlook<http://aka.ms/Ox5hz3>




On Tue, Oct 13, 2015 at 10:41 AM -0700, "ianapps" <notifications@github.com<mailto:notifications@github.com>> wrote:


It's in the exported code, You may not have any control of it, it may be a Cordova thing. The only thing i have to do now to generate a Universal app (that passes store certification) is make some images as Win10 image sizes are different from Win8.1 and update the plugins because they point to the wrong repository when TD generates the code. Overall I am delighted with TD and the work you and your team are doing - it's come a long way in the last 2 or 3 years.

-
