### ISSUE TITLE
Loading collaboration scripts is too slow

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/TouchDevelop#33]
It usually takes 7-10 seconds for https://storage.touchdevelop.com/sessions/collaborations/<groupid> to return. It is possible to improve the performance of that API?

**Comment by sebastianburckhardt** [comment]
This API is slow because it calls 
http://www.touchdevelop.com/api/<group>/users
many times to fetch all users in the group. I need to do that to check that the user who issued the query is really in the group (I don't allow non-members to see the list of collaborations).

The only way to speed this up is if the TD cloud has a more efficient way to query membership.

**Comment by sebastianburckhardt** [comment]
Michal suggested to use this API:

http://www.touchdevelop.com/api/wonm/groups/dkgoxwrq - this gives the group
http://www.touchdevelop.com/api/wonm/groups/icosklzj  - this gives 404

This seems to work and is of course way faster. I have updated the server.
