### ISSUE TITLE
CCGA: Blocking bug: Problem with Rename return parameter tutorial step 

### ISSUE THREAD

**Issue by PatPhillips1400** [Microsoft/TouchDevelop#331]
The Rename function does not appear to be working correctly. This was brought to my attention by a teacher trying to use the Custom Function tutorial 1 at http://aka.ms/FunctionsTutorial1. The problem occurs on step (star) 9 when the student is directed to create a custom function to calculate the average.
[error message in custom function tutorial 1.docx]
(https://github.com/Microsoft/TouchDevelop/files/35749/error.message.in.custom.function.tutorial.1.docx)
The exact problem occurs when they are told to create the return parameter, avg.

**Comment by millerv** [comment]
This was recently fixed via bug:  https://github.com/Microsoft/TouchDevelop/issues/319

**Comment by millerv** [comment]
Ah, went and reproduced the issue - yes, creating the return parameter is not working correctly.  This blocks completion of this tutorial.

**Comment by millerv** [comment]
Mistakenly thought this was bug #319, but it's not.
User Voice comment:  https://touchdevelop.uservoice.com/forums/329607-touch-develop/suggestions/10659558-functions-tutorial-1

**Comment by PatPhillips1400** [comment]
Thanks

**Comment by pelikhan** [comment]
@msprotz did you make changes on return values recently?

**Comment by millerv** [comment]
New related User Voice: https://touchdevelop.uservoice.com/forums/329607-touch-develop/suggestions/10738155-fix-aka-ms-encryptiontutorial

**Comment by millerv** [comment]
Trying in /latest now, no change - issue still appears as shown in above-linked video.

**Comment by millerv** [comment]
Oh, I can see it in /latest version number 0.0.149.2124

**Comment by msprotz** [comment]
The previous behavior has been reverted for non-microbit deployments.

The "outparam" convention is bad; we should at least mark it deprecated for now and encourage people to use return, so that eventually we can render the output parameters without a name, and disable assigning to them.

**Comment by pelikhan** [comment]
Valerie, can we retrofit the tutorials over time? Are videos impacted?

Sent from Outlook<http://aka.ms/Ox5hz3>




On Wed, Nov 18, 2015 at 3:09 PM -0800, "Jonathan Protzenko" <notifications@github.com<mailto:notifications@github.com>> wrote:


The previous behavior has been reverted for non-microbit deployments.

The "outparam" convention is bad; we should at least mark it deprecated for now and encourage people to use return, so that eventually we can render the output parameters without a name, and disable assigning to them.

-
