### ISSUE TITLE
Tutorial prompting: order of changing parameters

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#34]
This tutorial demonstrates two issues: http://tdev.ly/iuxvkndh
1. When changing the parameter for **set y(0)**, it would be best to delete the existing parameter 1st (not last) before being prompted for the new parameter.
2. (less serious) When changing "100" to "200", it would be best to delete the "1" then add the "2", not add the "2" then delete the "1".

**Comment by brian-swan** [comment]
Another example of this behavior is in this tutorial: http://tdev.ly/onkhcwsu (which is an example for issue #36).

**Comment by mmoskal** [comment]
This is expected. Sort of.

You have two lines:

    sprite->set_x(0)
    sprite->set_x(foo(0, 200))

The shortest edit (if you were to insert tokens one by one) between them is adding “foo(“ and “, 200)”. However, our editor inserts “foo(-100, 100)” at once. The diff engine sits in lower abstraction level and doesn’t know about it. It would be very complicated to teach it about it.

One workaround would be not to insert default parameters in guided tutorial mode. I.e., instead of inserting “set x(0)” when the user taps “set x” we would insert “set x([x])” where [x] is a red placeholder. We already do that for non-primitive datatypes when we cannot find a reasonable default. This would also apply to “random range([min], [max])” (which would fix problems with editing “100” into “200”).

Now, the problem is what if we want the defaults? Or maybe it’s OK to never use the defaults in tutorial mode? Peli, Brian?

**Comment by brian-swan** [comment]
I imagined that this might be a difficult issue to address. I like the idea of no default values when in tutorial mode, especially since no other language that I know of provides default values when you are writing code. i.e. **Not** providing default values is more realistic.

If you decide to pursue this, then I'm not sure I think that something like "[x]" is the best placeholder for a value. Could it be a "greyed-out" descriptor of the type? For example...

**board->create picture(**picture**)**
or
**math->random range(**number, number**)**

**Comment by mmoskal** [comment]
We already have it, and it uses the name of the argument:

[cid:image002.jpg@01D054EA.515F1290]

It would be easy to enable for all types when requested.

**Comment by mmoskal** [comment]
I've added {flags:nodefaults} macro, which disables default function parameters. You can see an example here:
http://tdev.ly/ggigajao

It's a global option for the entire tutorial.

**Comment by pelikhan** [comment]
Maybe this should be the default mode in expert + keyboard mode.

**Comment by mmoskal** [comment]
This disables all defaults, but some defaults are good. We should only disable stupid defaults (most of the time 0 and ""). I think that would require some annotations.

**Comment by pelikhan** [comment]
If a keyboard is available / expert, you should do like any other ide: provide parenthesis, but don’t add ,. Anyway, it’s worth a try.
