### ISSUE TITLE
Exported Cordova Script in-app pictures not available

### ISSUE THREAD

**Issue by ianapps** [Microsoft/TouchDevelop#375]
When running an exported Cordova script, any in-app pictures are not available.  This may be related to https://github.com/Microsoft/TouchDevelop/issues/329.  In Visual Studio the error indicates that the URI is incorrect when it performs the GET to access the picture..

**Comment by millerv** [comment]
User Voice link:  https://touchdevelop.uservoice.com/forums/329607-touch-develop/suggestions/10992282-fix-cordova-exported-script-in-app-pictures-githu

**Comment by ianapps** [comment]
Providing more information which I hope will help:

During Cordova export in TD we get the art resources deployed:
0068.089> cordova: writing e5d803ba-2909-4754-ea38-8e70483f858b/cordova/www/art/l0_vdlWuvNdw4SLEL66

which are also written to the following location (I resume when the platform is added)::

e5d803ba-2909-4754-ea38-8e70483f858b/cordova/platforms/windows/www/art/l0_vdlWuvNdw4SLEL66

When running the app in VS2015 we get:
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
GET - https://az31353.vo.msecnd.net/pub/./art/l0_vdlWuvNdw4SLEL66

The only instance I can find of the art resource is in 'precompiled.js' - cs.registerArtResource("Picture", "$vdlWuvNdw4SLEL66", ".\u002fart\u002fl0_vdlWuvNdw4SLEL66");  which doesn't seem to correspond to the error.

However, when debugging - 10:35:35.6525: File C:\Users\XXXXXX\e5d803ba-2909-4754-ea38-8e70483f858b\cordova\platforms\windows\www\cordova.js contains a script loader file reference (url = //Microsoft.WinJS.1.0/js/base.js, type = ) that could not be loaded because the path could not be resolved.

This seems to point to the error, but I am not clever enough to work out how to fix it.

**Comment by pelikhan** [comment]
Script id?

Sent from Outlook Mobile<https://aka.ms/qtex0l>




On Thu, Dec 10, 2015 at 2:58 AM -0800, "ianapps" <notifications@github.com<mailto:notifications@github.com>> wrote:


Providing more information which I hope will help:

During Cordova export in TD we get the art resources deployed:
0068.089> cordova: writing e5d803ba-2909-4754-ea38-8e70483f858b/cordova/www/art/l0_vdlWuvNdw4SLEL66

which are also written to the following location (I resume when the platform is added)::

e5d803ba-2909-4754-ea38-8e70483f858b/cordova/platforms/windows/www/art/l0_vdlWuvNdw4SLEL66

When running the app in VS2015 we get:
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
GET - https://az31353.vo.msecnd.net/pub/./art/l0_vdlWuvNdw4SLEL66<https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2faz31353.vo.msecnd.net%2fpub%2f.%2fart%2fl0_vdlWuvNdw4SLEL66&data=01%7c01%7cjhalleux%40microsoft.com%7cb7b6d867e58347a65b6108d30150d36c%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=H0iHVHABN93vE1hYT0hSWM67LpHMIm1DAG9XnDSh9uY%3d>

The only instance I can find of the art resource is in 'precompiled.js' - cs.registerArtResource("Picture", "$vdlWuvNdw4SLEL66", ".\u002fart\u002fl0_vdlWuvNdw4SLEL66"); which doesn't seem to correspond to the error.

However, when debugging - 10:35:35.6525: File C:\Users\XXXXXX\e5d803ba-2909-4754-ea38-8e70483f858b\cordova\platforms\windows\www\cordova.js contains a script loader file reference (url = //Microsoft.WinJS.1.0/js/base.js, type = ) that could not be loaded because the path could not be resolved.

This seems to point to the error, but I am not clever enough to work out how to fix it.

-

**Comment by ianapps** [comment]
/lrlzzdhyvu 

It also runs fine in a TD environment.
No changes to the pictures or the code that was used to display them since I last compiled this script.

**Comment by ianapps** [comment]
URL is actually  "https://az31353.vo.msecnd.net/pub/mfxzyc" not "https://az31353.vo.msecnd.net/pub/./art/l0_vdlWuvNdw4SLEL66"

However, it is stored locally when the local app is created in TD, so I don't understand why this is required.

**Comment by ianapps** [comment]
If it helps, when running the script (Windows 10) it picks up the splash screen which is in exactly the same place as the in-app art which it isn't finding.

**Comment by ianapps** [comment]
This is a very simple test app to use: /nhknocpgno to illustrate this issue

**Comment by ianapps** [comment]
Further information to prove there is an issue in 'wall-set background picture' when a script is exported with Cordova:

wall-set background picture (ABC) - doesn't work
ABC post to wall - does work

so I assigned ABC to a variable - PIC

wall-set background picture (PIC) doesn't work
PIC post to wall does work

This does matter as the background picture is under the text and fills the screen on whatever device you are using.  When you post a picture to the wall it just rescales.

The fault lies in the 'set background picture' pointer.  It is not pointing to the correct resource.

Can someone please acknowledge this so that I know that someone is reading it.

**Comment by millerv** [comment]
Posted over on User Voice as well, but the TD team is seeing your updates, it's just most of them are on holiday now until January.

**Comment by ianapps** [comment]
Exactly the same issue for box-set background picture with exported Cordova scripts

**Comment by ianapps** [comment]
I have this working (although I am not sure it is the correct way).  In the exported 'precompliled.js" where you register the in-app art resource (cs.registerArtResource), I have changed the URL from ".\u002fart\u002fxxxxxx" to "\u002fwww\u002fart\u002fxxxxxx".

I have had to make this amendment twice in my app as there are 2 art resources used within the script.

**Comment by ianapps** [comment]
Based on my, last comment, has there been any progress on this since it proved there was an issue with the exported code
