### ISSUE TITLE
CCGA Dutch tutorials: videos issues

### ISSUE THREAD

**Issue by ilabar** [Microsoft/TouchDevelop#449]
Hi,
please see videos issues and repro steps.

![image](https://cloud.githubusercontent.com/assets/15230722/13141467/65e278c0-d62f-11e5-92e2-b14948a36945.png)

Thanks,
Ilaria

**Comment by millerv** [comment]
The background showing black instead of white in the poster is "won't fix" - any instance of that kind of poster is fine.
All of the video links in the TDT26 Loop Tutorial have been fixed - I think I had updated to the corrected videos on the Azure storage, but forgot to mirror that in this particular tutorial.

**Comment by millerv** [comment]
No other issues with this reported, closing bug.
